#
#  Makefile
#  STM32CubeLLVM
#
#  Created by Constantin Dullo on 25.09.20.
#

include definition.make

# default action: build all
all:
	echo "BUILD ALL"
	echo $(FMODULES_CACHE_PATH)
	echo $(FBUILD_SESSION_FILE)
	echo $(INDEX_DIR)
	echo $(INDEX_STORE_PATH)
	echo $(GENERATED_FILES)
	echo $(OWN_TARGET_HEADERS)
	echo $(ALL_TARGET_HEADERS)
	echo $(PROJECT_HEADERS)
	echo $(CC)
	echo $(CXX)
	echo $(AS)
	echo $(CP)
	echo $(SZ)
	echo $(HEX)
	echo $(BIN)