#
#  Makefile
#  STM32CubeLLVM
#
#  Created by Constantin Dullo on 25.09.20.
#

FMODULES_CACHE_PATH = $(HOME)/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
FBUILD_SESSION_FILE = Session.modulevalidation
INDEX_DIR = $(BUILD_ROOT)/../../Index/
INDEX_STORE_PATH = $(INDEX_DIR)/DataStore

# default action: build all
all:
	echo "BUILD ALL"
	echo $(FMODULES_CACHE_PATH)
	echo $(FBUILD_SESSION_FILE)
	echo $(INDEX_DIR)
	echo $(INDEX_STORE_PATH)