#
#  Makefile
#  STM32CubeLLVM
#
#  Created by Constantin Dullo on 25.09.20.
#

FMODULES_CACHE_PATH = $(HOME)/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
FBUILD_SESSION_FILE = Session.modulevalidation
INDEX_DIR = $(BUILD_ROOT)/../../Index/
INDEX_STORE_PATH = $(INDEX_DIR)/DataStore
GENERATED_FILES = $(OBJROOT)/xCubeTest.build/Debug/Index.build/xCubeTest-generated-files.hmap
OWN_TARGET_HEADERS = $(OBJROOT)/xCubeTest.build/Debug/Index.build/xCubeTest-own-target-headers.hmap
ALL_TARGET_HEADERS = $(OBJROOT)/xCubeTest.build/Debug/Index.build/xCubeTest-all-target-headers.hmap
PROJECT_HEADERS = $(OBJROOT)/xCubeTest.build/Debug/Index.build/xCubeTest-project-headers.hmap

# default action: build all
all:
	echo "BUILD ALL"
	echo $(FMODULES_CACHE_PATH)
	echo $(FBUILD_SESSION_FILE)
	echo $(INDEX_DIR)
	echo $(INDEX_STORE_PATH)
	echo $(GENERATED_FILES)
	echo $(OWN_TARGET_HEADERS)
	echo $(ALL_TARGET_HEADERS)
	echo $(PROJECT_HEADERS)